# Generated by Django 3.1 on 2020-08-11 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_link',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_link', to='projects.projectlink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_link', to='projects.projectlink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='institution_link',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_link', to='projects.projectlink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_link', to='projects.projectlink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='play_store_link',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_store_link', to='projects.projectlink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_link', to='projects.projectlink'),
        ),
    ]
