# Generated by Django 4.2.16 on 2026-01-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Your Name', help_text='Full name displayed on the site', max_length=100)),
                ('contact_email', models.EmailField(default='contact@example.com', help_text='Email address where contact form submissions are sent', max_length=254)),
                ('display_email', models.EmailField(default='hello@example.com', help_text='Email address displayed publicly on the site', max_length=254)),
                ('github_username', models.CharField(default='yourusername', help_text='GitHub username (without @) - used for API calls', max_length=100)),
                ('github_url', models.URLField(default='https://github.com/yourusername', help_text='Full GitHub profile URL')),
                ('linkedin_username', models.CharField(default='yourusername', help_text='LinkedIn username', max_length=100)),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/yourusername/', help_text='Full LinkedIn profile URL')),
                ('copyright_text', models.CharField(default='Your Name. All rights reserved', help_text='Copyright text displayed in footer', max_length=200)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image (recommended size: 400x400px or larger, square aspect ratio)', null=True, upload_to='profile/')),
                ('profile_image_alt_text', models.CharField(default='Profile Photo', help_text='Alt text for profile image (for accessibility)', max_length=100)),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon (recommended size: 32x32px or 64x64px, .png or .ico format)', null=True, upload_to='favicon/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
