"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import ssl
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '5f2e!@#b1#$%6"?d6%^&ekf32%@!#$-*STe3n@#Piemt&^LeSg')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF Protection for HTTPS
# Required when using HTTPS with reverse proxy (like Traefik)
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS', 
    'http://localhost:8888,http://127.0.0.1:8888'
).split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nested_inline',
    'projects',
    'home',
    'resume',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': 
            [
                'portfolio/templates',
                os.path.join(BASE_DIR, 'projects/templates'),
                os.path.join(BASE_DIR, 'home/templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Edmonton'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Directories to search for static files during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'node_modules'),
]

# Directory where collected static files will be stored for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise static files configuration for production
# Updated for Django 4.2+ compatibility
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# WhiteNoise configuration
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh in development
WHITENOISE_USE_FINDERS = DEBUG  # Use finders in development
WHITENOISE_MIMETYPES = {
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.svg': 'image/svg+xml',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
}

# Default primary key field type for Django 4.2
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Allow iframes from same origin (needed for PDF modal)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Email configuration
# For development, use console backend to print emails to console
# For production, configure SMTP settings via environment variables
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', '')
CONTACT_EMAIL = os.getenv('CONTACT_EMAIL', '')

# Allow self-signed certificates for email server
# Set EMAIL_SSL_VERIFY=False in environment variables if using self-signed certs
EMAIL_SSL_CERTFILE = os.getenv('EMAIL_SSL_CERTFILE', None)
EMAIL_SSL_KEYFILE = os.getenv('EMAIL_SSL_KEYFILE', None)

# Monkey patch for self-signed certificates
if os.getenv('EMAIL_SSL_VERIFY', 'True').lower() == 'false':
    import smtplib
    
    # Store the original SMTP_SSL._get_socket method
    _original_get_socket = smtplib.SMTP_SSL._get_socket
    
    # Create a wrapper that uses a custom SSL context
    def _patched_get_socket(self, host, port, timeout):
        # Create context that doesn't verify certificates
        new_context = ssl.create_default_context()
        new_context.check_hostname = False
        new_context.verify_mode = ssl.CERT_NONE
        
        # Replace the instance's context
        self.context = new_context
        
        # Call original _get_socket
        return _original_get_socket(self, host, port, timeout)
    
    # Apply the patch
    smtplib.SMTP_SSL._get_socket = _patched_get_socket

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
